package lab7_joshuamartinez;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import sun.applet.Main;

public class Inicio extends javax.swing.JFrame {

    ArrayList<Archivos> lista = new ArrayList();
    ArrayList<NewCarpetas> lista2 = new ArrayList();

    public Inicio() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_MiUnidad = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_MiUnidad = new javax.swing.JList<>();
        pg_Mostrar = new javax.swing.JProgressBar();
        JD_Destacado = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_Destacado = new javax.swing.JList<>();
        pg_Mostrar2 = new javax.swing.JProgressBar();
        JD_Papelera = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_Papelera = new javax.swing.JList<>();
        pg_Mostrar3 = new javax.swing.JProgressBar();
        JD_Archivo = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        tf_Nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboExtension = new javax.swing.JComboBox<>();
        tf_Tamaño = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        popup_MiUnidad = new javax.swing.JPopupMenu();
        jmi_Destacado = new javax.swing.JMenuItem();
        jmi_Eliminar = new javax.swing.JMenuItem();
        popup_Destacado = new javax.swing.JPopupMenu();
        jmi_Pasar_MiUnidad = new javax.swing.JMenuItem();
        jmi_Pasar_Papelera = new javax.swing.JMenuItem();
        popup_Papelera = new javax.swing.JPopupMenu();
        jmi_Restaurar = new javax.swing.JMenuItem();
        jmi_Eliminar_Permanente = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_MiUnidad = new javax.swing.JMenuItem();
        jmi_Destacados = new javax.swing.JMenuItem();
        jmi_Papelera = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_CrearArchivo = new javax.swing.JMenuItem();
        jmi_CrearCarpeta = new javax.swing.JMenuItem();

        jl_MiUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_MiUnidadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_MiUnidad);

        pg_Mostrar.setString("");
        pg_Mostrar.setStringPainted(true);

        javax.swing.GroupLayout JD_MiUnidadLayout = new javax.swing.GroupLayout(JD_MiUnidad.getContentPane());
        JD_MiUnidad.getContentPane().setLayout(JD_MiUnidadLayout);
        JD_MiUnidadLayout.setHorizontalGroup(
            JD_MiUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_MiUnidadLayout.createSequentialGroup()
                .addGroup(JD_MiUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_MiUnidadLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_MiUnidadLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(pg_Mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        JD_MiUnidadLayout.setVerticalGroup(
            JD_MiUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_MiUnidadLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(pg_Mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jl_Destacado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_DestacadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_Destacado);

        pg_Mostrar2.setString("");
        pg_Mostrar2.setStringPainted(true);

        javax.swing.GroupLayout JD_DestacadoLayout = new javax.swing.GroupLayout(JD_Destacado.getContentPane());
        JD_Destacado.getContentPane().setLayout(JD_DestacadoLayout);
        JD_DestacadoLayout.setHorizontalGroup(
            JD_DestacadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_DestacadoLayout.createSequentialGroup()
                .addGroup(JD_DestacadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_DestacadoLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_DestacadoLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(pg_Mostrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        JD_DestacadoLayout.setVerticalGroup(
            JD_DestacadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_DestacadoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pg_Mostrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jl_Papelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_PapeleraMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jl_Papelera);

        pg_Mostrar3.setToolTipText("");
        pg_Mostrar3.setString("");
        pg_Mostrar3.setStringPainted(true);

        javax.swing.GroupLayout JD_PapeleraLayout = new javax.swing.GroupLayout(JD_Papelera.getContentPane());
        JD_Papelera.getContentPane().setLayout(JD_PapeleraLayout);
        JD_PapeleraLayout.setHorizontalGroup(
            JD_PapeleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_PapeleraLayout.createSequentialGroup()
                .addGroup(JD_PapeleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_PapeleraLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_PapeleraLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(pg_Mostrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        JD_PapeleraLayout.setVerticalGroup(
            JD_PapeleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_PapeleraLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pg_Mostrar3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        jLabel1.setText("Nombre");

        jLabel2.setText("Extension");

        cboExtension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".pdf", ".txt", ".docx", ".jpg", ".mp4" }));

        jLabel3.setText("Tamaño");

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_ArchivoLayout = new javax.swing.GroupLayout(JD_Archivo.getContentPane());
        JD_Archivo.getContentPane().setLayout(JD_ArchivoLayout);
        JD_ArchivoLayout.setHorizontalGroup(
            JD_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ArchivoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(JD_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(JD_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboExtension, 0, 234, Short.MAX_VALUE)
                    .addComponent(tf_Nombre)
                    .addComponent(tf_Tamaño))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_ArchivoLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        JD_ArchivoLayout.setVerticalGroup(
            JD_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ArchivoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(JD_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(JD_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(JD_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jmi_Destacado.setText("Mover a Destacado");
        jmi_Destacado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_DestacadoActionPerformed(evt);
            }
        });
        popup_MiUnidad.add(jmi_Destacado);

        jmi_Eliminar.setText("Eliminar");
        jmi_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_EliminarActionPerformed(evt);
            }
        });
        popup_MiUnidad.add(jmi_Eliminar);

        jmi_Pasar_MiUnidad.setText("Mover a Mi Unidad");
        jmi_Pasar_MiUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_Pasar_MiUnidadActionPerformed(evt);
            }
        });
        popup_Destacado.add(jmi_Pasar_MiUnidad);

        jmi_Pasar_Papelera.setText("Eliminar");
        jmi_Pasar_Papelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_Pasar_PapeleraActionPerformed(evt);
            }
        });
        popup_Destacado.add(jmi_Pasar_Papelera);

        jmi_Restaurar.setText("Restaurar");
        jmi_Restaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_RestaurarActionPerformed(evt);
            }
        });
        popup_Papelera.add(jmi_Restaurar);

        jmi_Eliminar_Permanente.setText("Eliminar Permanente");
        jmi_Eliminar_Permanente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_Eliminar_PermanenteActionPerformed(evt);
            }
        });
        popup_Papelera.add(jmi_Eliminar_Permanente);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menu");

        jmi_MiUnidad.setText("Mi Unidad");
        jmi_MiUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_MiUnidadActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_MiUnidad);

        jmi_Destacados.setText("Destacados");
        jmi_Destacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_DestacadosActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_Destacados);

        jmi_Papelera.setText("Papelera");
        jmi_Papelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_PapeleraActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_Papelera);

        jMenu2.setText("Agregar");

        jmi_CrearArchivo.setText("Crear Archivo");
        jmi_CrearArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_CrearArchivoActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_CrearArchivo);

        jmi_CrearCarpeta.setText("Crear Carpeta");
        jmi_CrearCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_CrearCarpetaActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_CrearCarpeta);

        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_MiUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_MiUnidadActionPerformed
        String lugar = "Mi Unidad";
        AdminPregress aa = new AdminPregress(pg_Mostrar, lugar);
        Thread pro = new Thread(aa);
        pro.start();
        jl_MiUnidad.setModel(new DefaultListModel<>());
        AdminMiUnidad am = new AdminMiUnidad("./Mi Unidad.cbm");
        am.cargarArchivo();
        DefaultListModel l = (DefaultListModel) jl_MiUnidad.getModel();
        for (NewCarpetas c : am.getListaC()) {
            l.addElement(c);
        }
        for (Archivos a : am.getListaA()) {
            l.addElement(a);
        }
        jl_MiUnidad.setModel(l);
        JD_MiUnidad.setModal(true);
        JD_MiUnidad.pack();
        JD_MiUnidad.setLocationRelativeTo(null);
        JD_MiUnidad.setVisible(true);
        JD_MiUnidad.setVisible(false);

    }//GEN-LAST:event_jmi_MiUnidadActionPerformed

    private void jmi_DestacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_DestacadosActionPerformed
        String lugar = "Destacado";
        AdminPregress aa = new AdminPregress(pg_Mostrar2, lugar);
        Thread pro = new Thread(aa);
        pro.start();
        jl_Destacado.setModel(new DefaultListModel<>());
        AdminDestacado am = new AdminDestacado("./Destacados.cbm");
        am.cargarArchivo();
        DefaultListModel l = (DefaultListModel) jl_Destacado.getModel();
        for (NewCarpetas c : am.getListaC()) {
            l.addElement(c);
        }
        for (Archivos a : am.getListaA()) {
            l.addElement(a);
        }
        jl_Destacado.setModel(l);
        JD_Destacado.setModal(true);
        JD_Destacado.pack();
        JD_Destacado.setLocationRelativeTo(null);
        JD_Destacado.setVisible(true);
        JD_Destacado.setVisible(false);
    }//GEN-LAST:event_jmi_DestacadosActionPerformed

    private void jmi_CrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_CrearArchivoActionPerformed
        JD_Archivo.setModal(true);
        JD_Archivo.pack();
        JD_Archivo.setLocationRelativeTo(null);
        JD_Archivo.setVisible(true);
        JD_Archivo.setVisible(false);

    }//GEN-LAST:event_jmi_CrearArchivoActionPerformed

    private void jmi_CrearCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_CrearCarpetaActionPerformed
        String Nombre, Link="";
        try {
            Nombre = JOptionPane.showInputDialog("Ingrese nombre de la carpeta");
            String link = Link2();
            Link += "dive.google.com/(" + link + ")";
            NewCarpetas c = new NewCarpetas(Nombre, Link);
            AdminMiUnidad ap = new AdminMiUnidad("./Mi Unidad.cbm");
            ap.cargarArchivo();
            ap.getListaC().add(c);
            lista2.add(c);
            ap.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Carpeta guardado exitosamente");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "No se guardo exitosamente");
        }

    }//GEN-LAST:event_jmi_CrearCarpetaActionPerformed

    private void jmi_PapeleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_PapeleraActionPerformed
        String lugar = "Papelera";
        AdminPregress aa = new AdminPregress(pg_Mostrar3, lugar);
        Thread pro = new Thread(aa);
        pro.start();
        jl_Papelera.setModel(new DefaultListModel<>());
        AdminPapelera am = new AdminPapelera("./Papelera.cbm");
        am.cargarArchivo();
        DefaultListModel l = (DefaultListModel) jl_Papelera.getModel();
        for (NewCarpetas c : am.getListaC()) {
            l.addElement(c);
        }
        for (Archivos a : am.getListaA()) {
            l.addElement(a);
        }
        jl_Papelera.setModel(l);
        JD_Papelera.setModal(true);
        JD_Papelera.pack();
        JD_Papelera.setLocationRelativeTo(null);
        JD_Papelera.setVisible(true);
        JD_Papelera.setVisible(false);
    }//GEN-LAST:event_jmi_PapeleraActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        String nombre, Link = "";
        String link = Link2();
        Link += "dive.google.com/(" + link + ")";
        try {
            nombre = tf_Nombre.getText();
            Double tamaño;
            tamaño = Double.parseDouble(tf_Tamaño.getText());
            Archivos a = new Archivos(nombre, Link, cboExtension.getSelectedItem().toString(), tamaño);
            AdminMiUnidad ap = new AdminMiUnidad("./Mi Unidad.cbm");
            ap.cargarArchivo();
            ap.getListaA().add(a);
            lista.add(a);
            ap.escribirArchivo();
            JOptionPane.showMessageDialog(JD_Archivo, "Archivo guardado exitosamente");
            tf_Nombre.setText("");
            tf_Tamaño.setText("");
            cboExtension.setSelectedIndex(0);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(JD_Archivo, "Archivo No se guardo exitosamente");

        }

    }//GEN-LAST:event_btnGuardarMouseClicked

    private void jl_MiUnidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_MiUnidadMouseClicked
        if (evt.isMetaDown()) {
            popup_MiUnidad.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jl_MiUnidadMouseClicked

    private void jmi_DestacadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_DestacadoActionPerformed
        try {
            jl_Destacado.setModel(new DefaultListModel<>());
            int posicion1 = jl_MiUnidad.getSelectedIndex();
            DefaultListModel l = (DefaultListModel) jl_MiUnidad.getModel();
            DefaultListModel l2 = (DefaultListModel) jl_Destacado.getModel();
            Object temp = l.get(posicion1);
            AdminDestacado ad = new AdminDestacado("./Destacados.cbm");
            ad.cargarArchivo();
            AdminMiUnidad am = new AdminMiUnidad("./Mi Unidad.cbm");
            am.cargarArchivo();
            if (temp instanceof NewCarpetas) {
                ad.getListaC().add((NewCarpetas) temp);
                l2.addElement(temp);
                for (int i = 0; i < am.getListaC().size(); i++) {
                    if (((NewCarpetas) temp).getNombre().equals(am.getListaC().get(i).getNombre())) {
                        am.getListaC().remove(i);
                    }
                }
            } else if (temp instanceof Archivos) {
                ad.getListaA().add((Archivos) temp);
                l2.addElement(temp);
                for (int i = 0; i < am.getListaA().size(); i++) {
                    if (((Archivos) temp).getNombre().equals(am.getListaA().get(i).getNombre())) {
                        am.getListaA().remove(i);
                    }
                }
            }
            am.escribirArchivo();
            ad.escribirArchivo();
            l.remove(posicion1);
            jl_MiUnidad.setModel(l);
            jl_Destacado.setModel(l2);

        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmi_DestacadoActionPerformed

    private void jmi_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_EliminarActionPerformed
        try {
            jl_Papelera.setModel(new DefaultListModel<>());
            int posicion1 = jl_MiUnidad.getSelectedIndex();
            DefaultListModel l = (DefaultListModel) jl_MiUnidad.getModel();
            DefaultListModel l2 = (DefaultListModel) jl_Papelera.getModel();
            Object temp = l.get(posicion1);
            AdminPapelera ad = new AdminPapelera("./Papelera.cbm");
            ad.cargarArchivo();
            AdminMiUnidad am = new AdminMiUnidad("./Mi Unidad.cbm");
            am.cargarArchivo();
            if (temp instanceof NewCarpetas) {
                ad.getListaC().add((NewCarpetas) temp);
                l2.addElement(temp);
                for (int i = 0; i < am.getListaC().size(); i++) {
                    if (((NewCarpetas) temp).getNombre().equals(am.getListaC().get(i).getNombre())) {
                        am.getListaC().remove(i);
                    }
                }
            } else if (temp instanceof Archivos) {
                ad.getListaA().add((Archivos) temp);
                l2.addElement(temp);
                for (int i = 0; i < am.getListaA().size(); i++) {
                    if (((Archivos) temp).getNombre().equals(am.getListaA().get(i).getNombre())) {
                        am.getListaA().remove(i);
                    }
                }
            }
            am.escribirArchivo();
            ad.escribirArchivo();
            l.remove(posicion1);
            jl_MiUnidad.setModel(l);
            jl_Papelera.setModel(l2);

        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmi_EliminarActionPerformed

    private void jmi_Pasar_MiUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_Pasar_MiUnidadActionPerformed
        try {
            jl_MiUnidad.setModel(new DefaultListModel<>());
            int posicion1 = jl_Destacado.getSelectedIndex();
            DefaultListModel l = (DefaultListModel) jl_Destacado.getModel();
            DefaultListModel l2 = (DefaultListModel) jl_MiUnidad.getModel();
            Object temp = l.get(posicion1);
            AdminMiUnidad ad = new AdminMiUnidad("./Mi Unidad.cbm");
            ad.cargarArchivo();
            AdminDestacado am = new AdminDestacado("./Destacados.cbm");
            am.cargarArchivo();
            if (temp instanceof NewCarpetas) {
                ad.getListaC().add((NewCarpetas) temp);
                l2.addElement(temp);
                for (int i = 0; i < am.getListaC().size(); i++) {
                    if (((NewCarpetas) temp).getNombre().equals(am.getListaC().get(i).getNombre())) {
                        am.getListaC().remove(i);
                    }
                }
            } else if (temp instanceof Archivos) {
                ad.getListaA().add((Archivos) temp);
                l2.addElement(temp);
                for (int i = 0; i < am.getListaA().size(); i++) {
                    if (((Archivos) temp).getNombre().equals(am.getListaA().get(i).getNombre())) {
                        am.getListaA().remove(i);
                    }
                }
            }
            am.escribirArchivo();
            ad.escribirArchivo();
            l.remove(posicion1);
            jl_Destacado.setModel(l);
            jl_MiUnidad.setModel(l2);

        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmi_Pasar_MiUnidadActionPerformed

    private void jl_DestacadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_DestacadoMouseClicked
        if (evt.isMetaDown()) {
            popup_Destacado.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jl_DestacadoMouseClicked

    private void jl_PapeleraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_PapeleraMouseClicked
        if (evt.isMetaDown()) {
            popup_Papelera.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jl_PapeleraMouseClicked

    private void jmi_Pasar_PapeleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_Pasar_PapeleraActionPerformed
        try {
            jl_Papelera.setModel(new DefaultListModel<>());
            int posicion1 = jl_Destacado.getSelectedIndex();
            DefaultListModel l = (DefaultListModel) jl_Destacado.getModel();
            DefaultListModel l2 = (DefaultListModel) jl_Papelera.getModel();
            Object temp = l.get(posicion1);
            AdminPapelera ad = new AdminPapelera("./Papelera.cbm");
            ad.cargarArchivo();
            AdminDestacado am = new AdminDestacado("./Destacados.cbm");
            am.cargarArchivo();
            if (temp instanceof NewCarpetas) {
                ad.getListaC().add((NewCarpetas) temp);
                l2.addElement(temp);
                for (int i = 0; i < am.getListaC().size(); i++) {
                    if (((NewCarpetas) temp).getNombre().equals(am.getListaC().get(i).getNombre())) {
                        am.getListaC().remove(i);
                    }
                }
            } else if (temp instanceof Archivos) {
                ad.getListaA().add((Archivos) temp);
                l2.addElement(temp);
                for (int i = 0; i < am.getListaA().size(); i++) {
                    if (((Archivos) temp).getNombre().equals(am.getListaA().get(i).getNombre())) {
                        am.getListaA().remove(i);
                    }
                }
            }
            am.escribirArchivo();
            ad.escribirArchivo();
            l.remove(posicion1);
            jl_Destacado.setModel(l);
            jl_Papelera.setModel(l2);

        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmi_Pasar_PapeleraActionPerformed

    private void jmi_RestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_RestaurarActionPerformed
        try {
            jl_MiUnidad.setModel(new DefaultListModel<>());
            int posicion1 = jl_Papelera.getSelectedIndex();
            DefaultListModel l = (DefaultListModel) jl_Papelera.getModel();
            DefaultListModel l2 = (DefaultListModel) jl_MiUnidad.getModel();
            Object temp = l.get(posicion1);
            AdminMiUnidad ad = new AdminMiUnidad("./Mi Unidad.cbm");
            ad.cargarArchivo();
            AdminPapelera am = new AdminPapelera("./Papelera.cbm");
            am.cargarArchivo();
            if (temp instanceof NewCarpetas) {
                ad.getListaC().add((NewCarpetas) temp);
                l2.addElement(temp);
                for (int i = 0; i < am.getListaC().size(); i++) {
                    if (((NewCarpetas) temp).getNombre().equals(am.getListaC().get(i).getNombre())) {
                        am.getListaC().remove(i);
                    }
                }
            } else if (temp instanceof Archivos) {
                ad.getListaA().add((Archivos) temp);
                l2.addElement(temp);
                for (int i = 0; i < am.getListaA().size(); i++) {
                    if (((Archivos) temp).getNombre().equals(am.getListaA().get(i).getNombre())) {
                        am.getListaA().remove(i);
                    }
                }
            }
            am.escribirArchivo();
            ad.escribirArchivo();
            l.remove(posicion1);
            jl_Papelera.setModel(l);
            jl_MiUnidad.setModel(l2);

        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmi_RestaurarActionPerformed

    private void jmi_Eliminar_PermanenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_Eliminar_PermanenteActionPerformed
        try {
            int posicion1 = jl_Papelera.getSelectedIndex();
            DefaultListModel l = (DefaultListModel) jl_Papelera.getModel();
            Object temp = l.get(posicion1);
            AdminPapelera am = new AdminPapelera("./Papelera.cbm");
            am.cargarArchivo();
            if (temp instanceof NewCarpetas) {
                for (int i = 0; i < am.getListaC().size(); i++) {
                    if (((NewCarpetas) temp).getNombre().equals(am.getListaC().get(i).getNombre())) {
                        am.getListaC().remove(i);
                    }
                }
            } else if (temp instanceof Archivos) {
                for (int i = 0; i < am.getListaA().size(); i++) {
                    if (((Archivos) temp).getNombre().equals(am.getListaA().get(i).getNombre())) {
                        am.getListaA().remove(i);
                    }
                }
            }
            am.escribirArchivo();
            l.remove(posicion1);
            jl_Papelera.setModel(l);

        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmi_Eliminar_PermanenteActionPerformed

    public String Link2() {
        Random r = new Random();
        int numero;
        String link = "";
        for (int i = 0; i < 10; i++) {
            numero = 48 + r.nextInt(122);
            if (numero >= 48 && numero <= 57) {
                Character caracter = (char) numero;
                link += caracter;
            } else if (numero >= 65 && numero <= 89) {
                Character caracter = (char) numero;
                link += caracter;
            } else if (numero >= 97 && numero <= 122) {
                Character caracter = (char) numero;
                link += caracter;
            } else {
                i--;
            }
        }
        return link;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JD_Archivo;
    private javax.swing.JDialog JD_Destacado;
    private javax.swing.JDialog JD_MiUnidad;
    private javax.swing.JDialog JD_Papelera;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboExtension;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> jl_Destacado;
    private javax.swing.JList<String> jl_MiUnidad;
    private javax.swing.JList<String> jl_Papelera;
    private javax.swing.JMenuItem jmi_CrearArchivo;
    private javax.swing.JMenuItem jmi_CrearCarpeta;
    private javax.swing.JMenuItem jmi_Destacado;
    private javax.swing.JMenuItem jmi_Destacados;
    private javax.swing.JMenuItem jmi_Eliminar;
    private javax.swing.JMenuItem jmi_Eliminar_Permanente;
    private javax.swing.JMenuItem jmi_MiUnidad;
    private javax.swing.JMenuItem jmi_Papelera;
    private javax.swing.JMenuItem jmi_Pasar_MiUnidad;
    private javax.swing.JMenuItem jmi_Pasar_Papelera;
    private javax.swing.JMenuItem jmi_Restaurar;
    private javax.swing.JProgressBar pg_Mostrar;
    private javax.swing.JProgressBar pg_Mostrar2;
    private javax.swing.JProgressBar pg_Mostrar3;
    private javax.swing.JPopupMenu popup_Destacado;
    private javax.swing.JPopupMenu popup_MiUnidad;
    private javax.swing.JPopupMenu popup_Papelera;
    private javax.swing.JTextField tf_Nombre;
    private javax.swing.JTextField tf_Tamaño;
    // End of variables declaration//GEN-END:variables
}
